version: "3.9"

services:
  tests_app:
    build: .
    command: "gunicorn -w 4 --bind 0.0.0.0:5000 wsgi"
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./:/app
    depends_on:
      - database
  database:
    image: postgres:15-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.self_signed
    ports:
      - 80:80
      - 443:443
    depends_on:
      - tests_app
