FROM nginx:alpine

RUN mkdir /etc/nginx/ssl &&\
    apk update && apk add openssl &&\
    openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048 &&\
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/domain.key -out /etc/nginx/ssl/domain.crt \
    -subj "/C=US"

COPY nginx.conf /etc/nginx/nginx.conf
COPY static     /var/www/html/static
